// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9QHPLMaviS8xxL8LF9V7Gp2JEF7VpuN8',
    appId: '1:1062373173390:web:827cc9dcaeaf40304441df',
    messagingSenderId: '1062373173390',
    projectId: 'cotoapp',
    authDomain: 'cotoapp.firebaseapp.com',
    storageBucket: 'cotoapp.firebasestorage.app',
    measurementId: 'G-CSJEE35Z8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTLmKgWnzJ0-8bHAgX6nP-Vg8kzfj5QHI',
    appId: '1:1062373173390:android:4ae1d2cfe4f884284441df',
    messagingSenderId: '1062373173390',
    projectId: 'cotoapp',
    storageBucket: 'cotoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7VoohNe_MMqoqUb1LFsDuMtFxMuBvUM',
    appId: '1:1062373173390:ios:2ae2af0624eb17504441df',
    messagingSenderId: '1062373173390',
    projectId: 'cotoapp',
    storageBucket: 'cotoapp.firebasestorage.app',
    iosBundleId: 'com.jbapps.vezino',
  );
}
